[package]
name = "advent_of_code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "day-01"
path = "src/01/main.rs"

[[bin]]
name = "day-02"
path = "src/02/main.rs"

[[bin]]
name = "day-03"
path = "src/03/main.rs"

[[bin]]
name = "day-04"
path = "src/04/main.rs"

[[bin]]
name = "day-05"
path = "src/05/main.rs"

[[bin]]
name = "day-06"
path = "src/06/main.rs"

[[bin]]
name = "day-07"
path = "src/07/main.rs"

[[bin]]
name = "day-08"
path = "src/08/main.rs"

[[bin]]
name = "day-09"
path = "src/09/main.rs"

[[bin]]
name = "day-10"
path = "src/10/main.rs"

[[bin]]
name = "day-11"
path = "src/11/main.rs"

[[bin]]
name = "day-12"
path = "src/12/main.rs"

[[bin]]
name = "day-13"
path = "src/13/main.rs"

[[bin]]
name = "day-14"
path = "src/14/main.rs"

[[bin]]
name = "day-15"
path = "src/15/main.rs"

[[bin]]
name = "day-16"
path = "src/16/main.rs"

[[bin]]
name = "day-17"
path = "src/17/main.rs"

[[bin]]
name = "day-18"
path = "src/18/main.rs"

[[bin]]
name = "day-19"
path = "src/19/main.rs"

[[bin]]
name = "day-20"
path = "src/20/main.rs"

[[bin]]
name = "day-21"
path = "src/21/main.rs"

[[bin]]
name = "day-22"
path = "src/22/main.rs"

[[bin]]
name = "day-23"
path = "src/23/main.rs"

[[bin]]
name = "day-24"
path = "src/24/main.rs"

[[bin]]
name = "day-25"
path = "src/25/main.rs"